spring:
  application:
    name: ABAC
  flyway:
#    schemas: abac
    enabled: true
  datasource:
    hikari:
#      schema: abac
      maximum-pool-size: 3
      idle-timeout: 10000
      connection-timeout: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      order_inserts: true
      order_updates: true
      id:
        new_generator_mappings: true
      jdbc:
        batch_size: 5000
        batch_versioned_data: true
        fetch_size: 5000
    open-in-view: false

token:
  secret: ${"secret":AUTH_SECRET}
  expire:
    minutes: 60